version: '3.8'
services:
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"      # MailDev web UI
      - "1025:1025"      # MailDev SMTP server
    environment:
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=1080

  rabbitmq:
    container_name: rabbitmq-new
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME} # RabbitMQ username
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD} # RabbitMQ password


networks:
  mynetwork:
