version: "2.1"
services:

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"      # MailDev web UI
      - "1025:1025"      # MailDev SMTP server
    environment:
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=1080

  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672